dish_manager/urls.py
from django.urls import path
from .views import (
    index,
    CookListView,
    CookDetailView,
    CookCreateView,
    CookUpdateView,
    CookDeleteView,
    DishListView,
    DishDetailView,
    DishCreateView,
    DishDeleteView,
    DishUpdateView,
    AssignNewView,
    DishTypeListView,
    DishTypeDetailView,
    DishTypeCreateView,
    IngredientListView,
    IngredientDetailView,
    IngredientCreateView,
    IngredientDeleteView,
    IngredientUpdateView,
    DishTypeUpdateView,
    DishTypeDeleteView,
)

urlpatterns = [
    path("", index, name="index"),
    path("cooks/", CookListView.as_view(), name="cook-list"),
    path("cooks/<int:pk>/", CookDetailView.as_view(), name="cook-detail"),
    path("cooks/create/", CookCreateView.as_view(), name="cook-create"),
    path("cooks/<int:pk>/update/", CookUpdateView.as_view(), name="cook-update"),
    path("cooks/<int:pk>/delete/", CookDeleteView.as_view(), name="cook-delete"),
    path("dish/", DishListView.as_view(), name="dish-list"),
    path("dish/<int:pk>/", DishDetailView.as_view(), name="dish-detail"),
    path("dish/create/", DishCreateView.as_view(), name="dish-create"),
    path("dish/<int:pk>/update/", DishUpdateView.as_view(), name="dish-update"),
    path("dish/<int:pk>/delete/", DishDeleteView.as_view(), name="dish-delete"),
    path("dish/<int:dish_id>/assign/", AssignNewView.as_view(), name="dish-assign"),
    path("Ingredient/", IngredientListView.as_view(), name="ingredient-list"),
    path(
        "Ingredient/<int:pk>/", IngredientDetailView.as_view(), name="ingredient-detail"
    ),
    path(
        "Ingredient/create/",
        IngredientCreateView.as_view(),
        name="ingredient-create",
    ),
    path(
        "Ingredient/<int:pk>/update/",
        IngredientUpdateView.as_view(),
        name="ingredient-update",
    ),
    path(
        "Ingredient/<int:pk>/delete/",
        IngredientDeleteView.as_view(),
        name="ingredient-delete",
    ),
    path("dishtype/", DishTypeListView.as_view(), name="dishtype-list"),
    path("dishtype/<int:pk>/", DishTypeDetailView.as_view(), name="dishtype-detail"),
    path("dishtype/create/", DishTypeCreateView.as_view(), name="dishtype-create"),
    path(
        "dishtype/<int:pk>/update/",
        DishTypeUpdateView.as_view(),
        name="dishtype-update",
    ),
    path(
        "dishtype/<int:pk>/delete/",
        DishTypeDeleteView.as_view(),
        name="dishtype-delete",
    ),
]

app_name = "dish_manager"

restaurant_kitchen_service/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("dish_manager.urls", namespace="dish_manager")),
    path("accounts/", include("django.contrib.auth.urls"))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/includes/footer.html
  <footer class="footer pt-5 mt-5">
    <hr class="horizontal dark mb-5">
    <div class="container">
      <div class="row">
        <div class="col-md-4 mb-4 ms-auto">
          <div>
            <h6 class="text-gradient text-primary font-weight-bolder">Restaurant Kitchen Service</h6>
          </div>
        </div>
        <div class="col-md-3 col-sm-6 col-6 mb-4">
          <div>
            <h6 class="text-gradient text-primary text-sm">Social</h6>
            <ul class="d-flex flex-row ms-n3 nav">
              <li class="nav-item">
                <a class="nav-link pe-1" href="https://www.facebook.com" target="_blank">
                  <i class="fab fa-facebook text-lg opacity-8"></i>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link pe-1" href="https://twitter.com" target="_blank">
                  <i class="fab fa-twitter text-lg opacity-8"></i>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link pe-1" href="https://www.instagram.com" target="_blank">
                  <i class="fab fa-instagram text-lg opacity-8"></i>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link pe-1" href="https://github.com/Vlad1slavo" target="_blank">
                  <i class="fab fa-github text-lg opacity-8"></i>
                </a>
              </li>
            </ul>
          </div>
        </div>
        <div class="col-md-3 col-sm-6 col-6 mb-4">
          <div>
            <h6 class="text-gradient text-primary text-sm">Developer Tool</h6>
            <ul class="flex-column ms-n3 nav">
              <li class="nav-item">
                <a class="nav-link" href="https://www.jetbrains.com/pycharm/" target="blank">
                  PyCharm
                </a>
              </li>
            </ul>
          </div>
        </div>
        <div class="col-md-2 col-sm-6 col-6 mb-4">
          <div>
            <h6 class="text-gradient text-primary text-sm">LinkedIn Profile</h6>
            <ul class="flex-column ms-n3 nav">
              <li class="nav-item">
                <a class="nav-link" href="https://www.linkedin.com/in/vladyslav-moiseienko-22987b257/" target="_blank">
                  Contact me
                </a>
              </li>
            </ul>
          </div>
        </div>
        <div class="col-12">
          <div class="text-center">
            <p class="my-4 text-sm">
              Restaurant Kitchen Service &copy; - Coded by <a target="_blank" href="https://github.com/Vlad1slavo" target="_blank">Vlad1slavo</a>.
            </p>
          </div>
        </div>
      </div>
    </div>
  </footer>

templates/includes/navigation.html
  <div class="container position-sticky z-index-sticky top-0">
    <div class="row">
      <div class="col-12">
        <nav class="navbar navbar-expand-lg  blur blur-rounded top-0 z-index-fixed shadow position-absolute my-3 py-2 start-0 end-0 mx-4">
          <div class="container-fluid">
            <a class="navbar-brand font-weight-bolder ms-sm-3" 
               href="/" rel="tooltip" title="Designed and Coded by Creative Tim" data-placement="bottom">
              Kitchen Manager
            </a>
            <button class="navbar-toggler shadow-none ms-2" type="button" data-bs-toggle="collapse" data-bs-target="#navigation" aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon mt-2">
                <span class="navbar-toggler-bar bar1"></span>
                <span class="navbar-toggler-bar bar2"></span>
                <span class="navbar-toggler-bar bar3"></span>
              </span>
            </button>
            <div class="collapse navbar-collapse pt-3 pb-2 py-lg-0" id="navigation">
              <ul class="navbar-nav navbar-nav-hover ms-lg-12 ps-lg-5 w-100">
                <li class="nav-item dropdown dropdown-hover mx-2">
                  <a class="nav-link ps-2 d-flex justify-content-between cursor-pointer align-items-center dropdown-item border-radius-md" href="{% url 'dish_manager:cook-list' %}">
                    Cooks
                  </a>
                </li>
                <li class="nav-item dropdown dropdown-hover mx-2">
                  <a class="nav-link ps-2 d-flex justify-content-between cursor-pointer align-items-center dropdown-item border-radius-md" href="{% url 'dish_manager:dish-list' %}">
                    Dishes
                  </a>
                </li>
                <li class="nav-item dropdown dropdown-hover mx-2">
                  <a class="nav-link ps-2 d-flex justify-content-between cursor-pointer align-items-center dropdown-item border-radius-md" href="{% url 'dish_manager:ingredient-list' %}">
                    Ingredients
                  </a>
                </li>
                <li class="nav-item dropdown dropdown-hover mx-2">
                  <a class="nav-link ps-2 d-flex justify-content-between cursor-pointer align-items-center dropdown-item border-radius-md" href="{% url 'dish_manager:dishtype-list' %}">
                    Dish types
                  </a>
                </li>
                <li class="nav-item">
                  <form method="post" action="{% url 'logout' %}?next={{request.path}}">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-link nav-link">
                      <i class="fa fa-sign-out me-1"></i>
                      <p class="d-inline text-sm z-index-1 font-weight-bold" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Logout">Logout</p>
                    </button>
                  </form>
                </li>
                <li class="nav-item my-auto ms-3 ms-lg-0">
                  <a href="{{ user.get_absolute_url }}"
                     class="btn btn-sm bg-gradient-primary btn-round mb-0 me-1 mt-2 mt-md-0">My profile</a>
                </li>
              </ul>
            </div>
          </div>
        </nav>
        <!-- End Navbar -->
      </div>
    </div>
  </div>

templates/includes/pagination.html
{% if is_paginated %}
  <ul class="pagination pagination-primary justify-content-center">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?page={{ page_obj.previous_page_number }}" class="page-link">
          <span aria-hidden="true"><i class="fa fa-angle-double-left" aria-hidden="true"></i></span>
        </a>
      </li>
    {% endif %}
    <li class="page-item active">
      <span class="page-link">{{ page_obj.number }}</span>
    </li>
    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?page={{ page_obj.next_page_number }}" class="page-link">
          <span aria-hidden="true"><i class="fa fa-angle-double-right" aria-hidden="true"></i></span>
        </a>
      </li>
    {% endif %}
  </ul>
{% endif %}

templates/includes/scripts.html
  <script src="/static/assets/js/core/popper.min.js" type="text/javascript"></script>
  <script src="/static/assets/js/core/bootstrap.min.js" type="text/javascript"></script>
  <script src="/static/assets/js/plugins/perfect-scrollbar.min.js"></script>
  <script src="/static/assets/js/plugins/prism.min.js"></script>
  <script src="/static/assets/js/plugins/parallax.min.js"></script>

templates/includes/search.html
{% load crispy_forms_filters %}
<form action="" method="get" class="form-inline">
  {{ search_form|crispy  }}
 </form>