dish_manager/urls.py
from django.urls import path
from .views import (
    index,
    CookListView,
    CookDetailView,
    CookCreateView,
    CookUpdateView,
    CookDeleteView,
    DishListView,
    DishDetailView,
    DishCreateView,
    DishDeleteView,
    DishUpdateView,
    AssignNewView,
    DishTypeListView,
    DishTypeDetailView,
    DishTypeCreateView,
    IngredientListView,
    IngredientDetailView,
    IngredientCreateView,
    IngredientDeleteView,
    IngredientUpdateView,
    DishTypeUpdateView,
    DishTypeDeleteView,
)

urlpatterns = [
    path("", index, name="index"),
    path("cooks/", CookListView.as_view(), name="cook-list"),
    path("cooks/<int:pk>/", CookDetailView.as_view(), name="cook-detail"),
    path("cooks/create/", CookCreateView.as_view(), name="cook-create"),
    path("cooks/<int:pk>/update/", CookUpdateView.as_view(), name="cook-update"),
    path("cooks/<int:pk>/delete/", CookDeleteView.as_view(), name="cook-delete"),
    path("dish/", DishListView.as_view(), name="dish-list"),
    path("dish/<int:pk>/", DishDetailView.as_view(), name="dish-detail"),
    path("dish/create/", DishCreateView.as_view(), name="dish-create"),
    path("dish/<int:pk>/update/", DishUpdateView.as_view(), name="dish-update"),
    path("dish/<int:pk>/delete/", DishDeleteView.as_view(), name="dish-delete"),
    path("dish/<int:dish_id>/assign/", AssignNewView.as_view(), name="dish-assign"),
    path("Ingredient/", IngredientListView.as_view(), name="ingredient-list"),
    path(
        "Ingredient/<int:pk>/", IngredientDetailView.as_view(), name="ingredient-detail"
    ),
    path(
        "Ingredient/create/",
        IngredientCreateView.as_view(),
        name="ingredient-create",
    ),
    path(
        "Ingredient/<int:pk>/update/",
        IngredientUpdateView.as_view(),
        name="ingredient-update",
    ),
    path(
        "Ingredient/<int:pk>/delete/",
        IngredientDeleteView.as_view(),
        name="ingredient-delete",
    ),
    path("dishtype/", DishTypeListView.as_view(), name="dishtype-list"),
    path("dishtype/<int:pk>/", DishTypeDetailView.as_view(), name="dishtype-detail"),
    path("dishtype/create/", DishTypeCreateView.as_view(), name="dishtype-create"),
    path(
        "dishtype/<int:pk>/update/",
        DishTypeUpdateView.as_view(),
        name="dishtype-update",
    ),
    path(
        "dishtype/<int:pk>/delete/",
        DishTypeDeleteView.as_view(),
        name="dishtype-delete",
    ),
]

app_name = "dish_manager"

restaurant_kitchen_service/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("dish_manager.urls", namespace="dish_manager")),
    path("accounts/", include("django.contrib.auth.urls"))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

dish_manager/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse


class Cook(AbstractUser):
    years_of_experience = models.IntegerField(default=0)

    class Meta:
        verbose_name = "cook"
        verbose_name_plural = "cooks"

    def __str__(self):
        return f"{self.username} ({self.first_name} {self.last_name})"

    def get_absolute_url(self):
        return reverse("dish_manager:cook-detail", kwargs={"pk": self.pk})


class DishType(models.Model):
    name = models.CharField(max_length=100)

    class Meta:
        ordering = ["name"]
        verbose_name = "DishType"
        verbose_name_plural = "DishTypes"

    def __str__(self):
        return self.name


class Dish(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    price = models.DecimalField(max_digits=5, decimal_places=2)
    dishtype = models.ForeignKey(
        DishType, on_delete=models.CASCADE, related_name="dishes"
    )
    cooks = models.ManyToManyField(Cook, related_name="dishes")

    class Meta:
        ordering = ["name"]
        verbose_name = "Dish"
        verbose_name_plural = "Dishes"

    def __str__(self):
        return self.name


class Ingredient(models.Model):
    name = models.CharField(max_length=100)
    dishes = models.ManyToManyField(Dish, related_name="ingredients")

    class Meta:
        ordering = ["name"]
        verbose_name = "Ingredient"
        verbose_name_plural = "Ingredients"

    def __str__(self):
        return f"{self.name} in {self.dishes}"

dish_manager/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError

from dish_manager.models import Dish


class CookCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = UserCreationForm.Meta.fields + (
            "first_name",
            "last_name",
            "years_of_experience",
            "email",
        )

    def clean_years(self):
        return validate_years(self.cleaned_data["years_of_experience"])


class DishForm(forms.ModelForm):
    cooks = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(), widget=forms.CheckboxSelectMultiple
    )

    class Meta:
        model = Dish
        fields = "__all__"


class CookUpdateForm(forms.ModelForm):
    class Meta:
        model = get_user_model()
        fields = ["first_name", "last_name", "years_of_experience", "email"]


def validate_years(years_of_experience):
    if years_of_experience > 100:
        raise ValidationError("Its impossible")
    if not years_of_experience.isdigit():
        raise ValidationError("Years of experience must be digits only")
    return years_of_experience


class IngredientSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by name..."}),
    )


class DishSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by name..."}),
    )


class DishTypeSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by name..."}),
    )


class CookSearchForm(forms.Form):
    username = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by username..."}),
    )

dish_manager/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from django.views import generic, View
from django.contrib.auth.mixins import LoginRequiredMixin


from .forms import (
    CookCreationForm,
    DishForm,
    CookUpdateForm,
    IngredientSearchForm,
    DishTypeSearchForm,
    DishSearchForm,
    CookSearchForm,
)
from .models import Cook, Dish, DishType, Ingredient


@login_required
def index(request):
    """View function for the home page of the site."""

    num_cooks = Cook.objects.count()
    num_dishes = Dish.objects.count()
    num_dishtypes = DishType.objects.count()
    num_ingredients = Ingredient.objects.count()

    num_visits = request.session.get("num_visits", 0)
    request.session["num_visits"] = num_visits + 1

    context = {
        "num_cooks": num_cooks,
        "num_dishes": num_dishes,
        "num_dishtypes": num_dishtypes,
        "num_ingredients": num_ingredients,
        "num_visits": num_visits + 1,
    }

    return render(request, "dish_manager/index.html", context=context)


class CookListView(LoginRequiredMixin, generic.ListView):
    model = Cook
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(CookListView, self).get_context_data(**kwargs)

        username = self.request.GET.get("username", "")

        context["search_form"] = CookSearchForm(initial={"username": username})

        return context

    def get_queryset(self):
        queryset = Cook.objects.all()
        form = CookSearchForm(self.request.GET)

        if form.is_valid():
            return queryset.filter(username__icontains=form.cleaned_data["username"])

        return queryset


class CookCreateView(LoginRequiredMixin, generic.CreateView):
    model = get_user_model()
    form_class = CookCreationForm
    success_url = reverse_lazy("dish_manager:cook-list")


class CookUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = get_user_model()
    form_class = CookUpdateForm
    success_url = reverse_lazy("dish_manager:cook-list")


class CookDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = get_user_model()
    success_url = reverse_lazy("dish_manager:cook-list")


class CookDetailView(LoginRequiredMixin, generic.DetailView):
    model = get_user_model()
    queryset = Cook.objects.all().prefetch_related("dishes__dishtype")


class AssignNewView(LoginRequiredMixin, View):
    def post(self, request: HttpRequest, dish_id: int) -> HttpResponse:
        cook = get_object_or_404(Cook, id=request.user.id)
        dish = get_object_or_404(Dish, id=dish_id)
        if cook in dish.cooks.all():
            dish.cooks.remove(cook)
        else:
            dish.cooks.add(cook)

        return HttpResponseRedirect(
            reverse_lazy("dish_manager:dish-detail", args=[dish_id])
        )


class DishListView(LoginRequiredMixin, generic.ListView):
    model = Dish
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(DishListView, self).get_context_data(**kwargs)

        name = self.request.GET.get("name", "")

        context["search_form"] = DishSearchForm(initial={"name": name})

        return context

    def get_queryset(self):
        queryset = Dish.objects.select_related("dishtype")
        form = DishSearchForm(self.request.GET)

        if form.is_valid():
            return queryset.filter(name__icontains=form.cleaned_data["name"])

        return queryset


class DishDetailView(LoginRequiredMixin, generic.DetailView):
    model = Dish
    queryset = Dish.objects.all().prefetch_related("ingredients", "cooks")


class DishCreateView(LoginRequiredMixin, generic.CreateView):
    model = Dish
    form_class = DishForm
    success_url = reverse_lazy("dish_manager:dish-list")


class DishUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Dish
    form_class = DishForm
    success_url = reverse_lazy("dish_manager:dish-list")


class DishDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Dish
    success_url = reverse_lazy("dish_manager:dish-list")


class DishTypeListView(LoginRequiredMixin, generic.ListView):
    model = DishType
    context_object_name = "dishtype_list"
    template_name = "dish_manager/dishtype_list.html"
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(DishTypeListView, self).get_context_data(**kwargs)

        name = self.request.GET.get("name", "")

        context["search_form"] = DishTypeSearchForm(initial={"name": name})

        return context

    def get_queryset(self):
        queryset = DishType.objects.all()
        form = DishTypeSearchForm(self.request.GET)

        if form.is_valid():
            return queryset.filter(name__icontains=form.cleaned_data["name"])

        return queryset


class DishTypeDetailView(LoginRequiredMixin, generic.DetailView):
    model = DishType


class DishTypeCreateView(LoginRequiredMixin, generic.CreateView):
    model = DishType
    fields = "__all__"
    template_name = "dish_manager/dishtype_form.html"
    success_url = reverse_lazy("dish_manager:dishtype-list")


class DishTypeUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = DishType
    fields = "__all__"
    template_name = "dish_manager/dishtype_form.html"
    success_url = reverse_lazy("dish_manager:dishtype-list")


class DishTypeDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = DishType
    template_name = "dish_manager/dishtype_confirm_delete.html"
    success_url = reverse_lazy("dish_manager:dishtype-list")


class IngredientListView(LoginRequiredMixin, generic.ListView):
    model = Ingredient
    context_object_name = "ingredient_list"
    template_name = "dish_manager/ingredient_list.html"
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(IngredientListView, self).get_context_data(**kwargs)

        name = self.request.GET.get("name", "")

        context["search_form"] = IngredientSearchForm(initial={"name": name})

        return context

    def get_queryset(self):
        queryset = Ingredient.objects.all()
        form = IngredientSearchForm(self.request.GET)

        if form.is_valid():
            return queryset.filter(name__icontains=form.cleaned_data["name"])

        return queryset


class IngredientDetailView(LoginRequiredMixin, generic.DetailView):
    model = Ingredient
    queryset = Ingredient.objects.all().prefetch_related("dishes")


class IngredientCreateView(LoginRequiredMixin, generic.CreateView):
    model = Ingredient
    fields = "__all__"
    success_url = reverse_lazy("dish_manager:ingredient-list")


class IngredientUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Ingredient
    fields = "__all__"
    success_url = reverse_lazy("dish_manager:ingredient-list")


class IngredientDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Ingredient
    success_url = reverse_lazy("dish_manager:ingredient-list")

templates/dish_manager/cook_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  {% include "includes/navigation.html" %}
  <section class="pt-9 position-relative">
    <div class="container">
      <h1>Delete Cook</h1>

      <p>Are you sure you want to delete cook: {{ cook }}?</p>

      <form action="" method="post">
        {% csrf_token %}
        <input type="submit" value="Yes, delete" class="btn bg-gradient-danger w-auto" />
        <input type="button" class="btn bg-gradient-light" onclick="history.back();" value="Cancel"/>
      </form>
    </div>
  </section>
{% endblock %}

templates/dish_manager/cook_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  {% include "includes/navigation.html" %}
  <section class="pt-9 position-relative">
    <div class="container">
      <h1 class="pb-3">{{ object|yesno:"Update,Create" }} Cooker</h1>
      <form action="" method="post" novalidate>
        {% csrf_token %}
        {{ form|crispy }}

        <input type="submit" value="Submit" class="btn bg-gradient-primary">
      </form>
    </div>
  </section>
{% endblock %}

templates/dish_manager/dish_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  {% include "includes/navigation.html" %}
  <section class="pt-9 position-relative">
    <div class="container">
      <h1>Delete dish</h1>

      <p>Are you sure you want to delete dish: {{ dish }}?</p>

      <form action="" method="post">
        {% csrf_token %}
        <input type="submit" value="Yes, delete" class="btn bg-gradient-danger w-auto" />
        <input type="button" class="btn bg-gradient-light" onclick="history.back();" value="Cancel"/>
      </form>
    </div>
  </section>
{% endblock %}

templates/dish_manager/dish_detail.html
{% extends "base.html" %}

{% block title %} {{ dish.id }} {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block body_class %} blog-author bg-gray-100 {% endblock body_class %}

{% block content %}

  {% include "includes/navigation.html" %}

   <section class="py-sm-5 py-5 position-relative">

    <div class="container">
      <div class="row">
        <div class="col-12 mx-auto">
          <div class="row pt-7">

            <div class="col-md-9 col-sm-6 col-6 mb-4">
              <h1>{{ dish.name }}</h1>
            </div>
            <div class="col-md-3 col-sm-6 col-6 mb-4">
              <div class="m-3">
              <a href="{% url 'dish_manager:dish-update' pk=dish.id %}" class="btn btn-sm btn-outline-info w-auto">
                Update
              </a>
              <a href="{% url 'dish_manager:dish-delete' pk=dish.id %}" class="btn btn-sm btn-outline-secondary w-auto">
                Delete
              </a>
              </div>
            </div>

          </div>
          <div class="row mb-4">
            <div class="col-auto">
              <span>Type:</span>
              <span class="h6">{{ dish.dishtype.name }}</span>
            </div>

            <div class="col-auto">
              <span>Price:</span>
              <span class="h6 text-success">{{ dish.price }}</span>
            </div>
          </div>
        </div>
      </div>
    </div>

  </section>

  <div class="container">
  
    <div class="row pt-5">
      <div class="col-lg-12">
        <h3 class="mb-5">
          <span class="text-primary">Description:</span>
        </h3>
        <hr>
        <p>
          {{ dish.description }}
        </p>
      </div>
    </div>
    <div class="row pt-5">
      <div class="col-lg-12">
        <h3 class="mb-5">
          <span class="text-primary">Ingredients:</span>
        </h3>
        <hr>
        <ul>
          {% for ingredient in dish.ingredients.all %}
          <li>{{ ingredient.name }}</li>
          {% empty %}
          <li>No ingredients have been added to this dish yet.</li>
          {% endfor %}
        </ul>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-12">
        <h3 class="mb-5">
          <span class="text-primary">Cooks:</span>
          <div class="me-4 m-3 float-end">
            <form method="post" action="{% url 'dish_manager:dish-assign' dish_id=dish.id %}">
              {% csrf_token %}
              {% if dish not in request.user.dishes.all %}
                <button type="submit" class="btn btn-sm btn-outline-success w-auto">
                  Assign me to this dish
                </button>
              {% else %}
                <button type="submit" class="btn btn-sm btn-outline-danger w-auto">
                  Delete me from this dish
                </button>
              {% endif %}
            </form>
          </div>
        </h3>
        <hr>
        <ul>
          {% for cook in dish.cooks.all %}
          <li><a href="{{ cook.get_absolute_url }}">{{ cook.first_name }} {{ cook.last_name }}</a></li>
          {% endfor %}
        </ul>
      </div>
    </div>

  </div>
{% endblock %}

templates/dish_manager/dish_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  {% include "includes/navigation.html" %}
  <section class="pt-9 position-relative">
    <div class="container">
      <h1 class="pb-3">{{ object|yesno:"Update,Create" }} dish</h1>
      <form action="" method="post" novalidate>
        {% csrf_token %}
        {{ form|crispy }}

        <input type="submit" value="Submit" class="btn bg-gradient-primary">
      </form>
    </div>
  </section>
{% endblock %}

templates/dish_manager/dish_list.html
{% extends "base.html" %}

{% block title %}Dishes{% endblock title %}

{% block content %}
  {% include "includes/navigation.html" %}
  <header class="section-height-25">
  </header>
  <div class="container">
    <h1>
      Dish List
      <a href="{% url 'dish_manager:dish-create' %}" class="btn bg-gradient-secondary w-auto me-5 m-3 float-end">
        Create
      </a>
    </h1>
    <br>
    {% block search %}
      {% include "includes/search.html" %}
    {% endblock %}
    <br>
    {% if dish_list %}

    <table class="table">
      <tr>
        <th class="text-gradient text-primary font-weight-bolder" style="width: 30%">Name</th>
        <th class="text-gradient text-primary font-weight-bolder" style="width: 18%">Dish type</th>
        <th class="text-gradient text-primary font-weight-bolder" style="width: 20%">Price</th>
        <th class="text-gradient text-primary font-weight-bolder" style="width: 16%">Cook</th>
      </tr>
    {% for dish in dish_list %}
      <tr>
        <td><a href="{% url "dish_manager:dish-detail" pk=dish.id %} ">{{ dish.name }}</a></td>
        <td>{{ dish.dishtype.name }}</td>
        <td>{{ dish.price }}</td>
        <td>{{ dish.cooks.count }}</td>
      </tr>
    {% endfor %}
    </table>
    {% include "includes/pagination.html" %}
    {% else %}
      <p>There are no dishes.</p>
    {% endif %}
  </div>
{% endblock %}

templates/dish_manager/dishtype_detail.html
{% extends "base.html" %}

{% block title %} {{ dishtype.name }} {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block body_class %} blog-author bg-gray-100 {% endblock body_class %}

{% block content %}

  {% include "includes/navigation.html" %}

  <section class="py-sm-5 py-5 position-relative">

    <div class="container">
      <div class="row">
        <div class="col-12 mx-auto">
          <div class="row pt-7">

            <div class="col-md-9 col-sm-6 col-6 mb-4">
              <h1>{{ dishtype.name }}</h1>
            </div>

          </div>
          <div class="row mb-4">
            <div class="col-auto">
              <span>Dishes:</span>
              <ul>
                {% for dish in dishtype.dishes.all %}
                <li><a href="{% url "dish_manager:dish-detail" pk=dish.id %} ">{{ dish.name }}</a></li>
                {% empty %}
                <li>No dishes have been added to this category yet.</li>
                {% endfor %}
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>

  </section>

{% endblock %}

templates/dish_manager/dishtype_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  {% include "includes/navigation.html" %}
  <section class="pt-9 position-relative">
    <div class="container">
      <h1 class="pb-3">{{ object|yesno:"Update,Create" }} Dish type</h1>
      <form action="" method="post" novalidate>
        {% csrf_token %}
        {{ form|crispy }}

        <input type="submit" value="Submit" class="btn bg-gradient-primary">
      </form>
    </div>
  </section>
{% endblock %}

templates/dish_manager/dishtype_list.html
{% extends "base.html" %}

{% block title %}Dish Types{% endblock title %}

{% block content %}
  {% include "includes/navigation.html" %}
  <header class="section-height-25">
  </header>
  <div class="container">
    <h1>
      Dish Type List
      <a href="{% url 'dish_manager:dishtype-create' %}" class="btn bg-gradient-secondary w-auto me-5 m-3 float-end">
        Create
      </a>
    </h1>
    <br>
    {% block search %}
      {% include "includes/search.html" %}
    {% endblock %}
    <br>
    {% if dishtype_list %}
    <table class="table">
      <tr>
        <th class="text-gradient text-primary font-weight-bolder" style="width: 30%">Name</th>
        <th class="text-gradient text-primary font-weight-bolder" style="width: 30%">Dishes in this category</th>
      </tr>
    {% for dishtype in dishtype_list %}
      <tr>
        <td><a href="{% url "dish_manager:dishtype-detail" pk=dishtype.id %} ">{{ dishtype.name }}</a></td>
        <td>{{ dishtype.dishes.count }}</td>
        <td>
          <a href="{% url 'dish_manager:dishtype-update' pk=dishtype.id %}" class="btn bg-gradient-info w-auto me-2 mb-0">
            Update
          </a>
        </td>
        <td>
          <a href="{% url 'dish_manager:dishtype-delete' pk=dishtype.id %}" class="btn bg-gradient-light w-auto me-2 mb-0">
            Delete
          </a>
        </td>
      </tr>
    {% endfor %}
    </table>
    {% include "includes/pagination.html" %}
    {% else %}
      <p>There are no dish types now.</p>
    {% endif %}
  </div>
{% endblock %}

templates/dish_manager/ingredient_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  {% include "includes/navigation.html" %}
  <section class="pt-9 position-relative">
    <div class="container">
      <h1>Delete Ingredient</h1>

      <p>Are you sure you want to delete ingredient: {{ ingredient }}?</p>

      <form action="" method="post">
        {% csrf_token %}
        <input type="submit" value="Yes, delete" class="btn bg-gradient-danger w-auto" />
        <input type="button" class="btn bg-gradient-light" onclick="history.back();" value="Cancel"/>
      </form>
    </div>
  </section>
{% endblock %}

templates/dish_manager/ingredient_detail.html
{% extends "base.html" %}

{% block title %} {{ ingredient.name }} {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block body_class %} blog-author bg-gray-100 {% endblock body_class %}

{% block content %}

  {% include "includes/navigation.html" %}

  <section class="py-sm-5 py-5 position-relative">

    <div class="container">
      <div class="row">
        <div class="col-12 mx-auto">
          <div class="row pt-7">

            <div class="col-md-9 col-sm-6 col-6 mb-4">
              <h1>{{ ingredient.name }}</h1>
            </div>

          </div>
          <div class="row mb-4">
            <div class="col-auto">
              <span>Dishes:</span>
              <ul>
                {% for dish in ingredient.dishes.all %}
                <li><a href="{% url "dish_manager:dish-detail" pk=dish.id %} ">{{ dish.name }}</a></li>
                {% empty %}
                <li>No dishes have been added to this category yet.</li>
                {% endfor %}
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>

  </section>

{% endblock %}

templates/dish_manager/ingredient_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  {% include "includes/navigation.html" %}
  <section class="pt-9 position-relative">
    <div class="container">
      <h1 class="pb-3">{{ object|yesno:"Update,Create" }} ingredient</h1>
      <form action="" method="post" novalidate>
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" value="Submit" class="btn bg-gradient-primary">
      </form>
    </div>
  </section>
{% endblock %}

templates/dish_manager/ingredient_list.html
{% extends "base.html" %}

{% block title %}Ingredients{% endblock title %}

{% block content %}
  {% include "includes/navigation.html" %}
  <header class="section-height-25">
  </header>
  <div class="container">
    <h1>
      Ingredient List
      <a href="{% url 'dish_manager:ingredient-create' %}" class="btn bg-gradient-secondary w-auto me-5 m-3 float-end">
        Create
      </a>
    </h1>
    <br>
    {% block search %}
      {% include "includes/search.html" %}
    {% endblock %}
    <br>
    {% if ingredient_list %}
    <table class="table">
      <tr>
        <th class="text-gradient text-primary font-weight-bolder" style="width: 60%">Name</th>
        <th class="text-gradient text-primary font-weight-bolder" style="width: 60%">Dishes</th>
        <th class="text-gradient text-primary font-weight-bolder" style="width: 17%">Update</th>
        <th class="text-gradient text-primary font-weight-bolder" style="width: 13%">Delete</th>
      </tr>
    {% for ingredient in ingredient_list %}
      <tr>
        <td><a href="{% url "dish_manager:ingredient-detail" pk=ingredient.id %} ">{{ ingredient.name }}</a></td>
        <td>{{ ingredient.dishes.count }}</td>
        <td>
          <a href="{% url 'dish_manager:ingredient-update' pk=ingredient.id %}" class="btn bg-gradient-info w-auto me-2 mb-0">
            Update
          </a>
        </td>
        <td>
          <a href="{% url 'dish_manager:ingredient-delete' pk=ingredient.id %}" class="btn bg-gradient-light w-auto me-2 mb-0">
            Delete
          </a>
        </td>
      </tr>
    {% endfor %}
    </table>
    {% include "includes/pagination.html" %}
    {% else %}
      <p>There are no ingredients in the company.</p>
    {% endif %}
  </div>
{% endblock %}